[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
film_token = "HX1rKo8hZgRbBvkSqQqhZw9gL5pff5BpPDrd8trdKumY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ikaaasra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
